#!/bin/bash
yum update
yum install software-properties-common -y
yum -add-repository --yes --update ppa:ansible/ansible
yum update
yum install ansible nginx python-apt git stress -y
git clone -b main https://github.com/venkatamalle/ansibletemplatetesting-master.git /myrepo
######USE aws-autoscaling branch for testing aws autoscaling##########################
######GIVE ONLY ABOVE IN THE USER DATA FOR AMI IMAGE FOR AWS AUTOSCALING##########
#
#####GIVE BELOW IN THE LAUNCH CONFIG USERDATA#####################################
ansible-playbook /myrepo/playbook.yaml
