#!/bin/bash
sudo yum update -y
sudo amazon-linux-extras enable epel -y
sudo yum install epel-release -y
sudo yum install -y ansible nginx python3 python3-pip git stress
sudo pip3 install boto boto3
sudo systemctl start nginx
sudo systemctl enable nginx
git clone -b main https://github.com/venkatamalle/ansibletemplatetesting-master.git /myrepo

######USE aws-autoscaling branch for testing aws autoscaling##########################
######GIVE ONLY ABOVE IN THE USER DATA FOR AMI IMAGE FOR AWS AUTOSCALING##########
#
#####GIVE BELOW IN THE LAUNCH CONFIG USERDATA#####################################
ansible-playbook /myrepo/playbook.yaml
